<?php

namespace AppBundle\Repository;

/**
 * ingredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ingredientsRepository extends \Doctrine\ORM\EntityRepository
{
}
