<?php

namespace AppBundle\Repository;

/**
 * recipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recipeRepository extends \Doctrine\ORM\EntityRepository
{
}
