<?php

namespace AppBundle\Repository;

/**
 * fridgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fridgeRepository extends \Doctrine\ORM\EntityRepository
{
}
