<?php

namespace AppBundle\Repository;

/**
 * RecipeHasIngRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeHasIngRepository extends \Doctrine\ORM\EntityRepository
{
}
